### PR TITLE
restore: Pending fixes for iOS 12.1 and iOS 12.1.1

### PR DESCRIPTION
**Pull request by Blefish**
Seems like a new feature in iOS 12 restore mode, where it prints these messages quite often. Since these are not handled elsewhere, they are printed out to stdout as plist.

### CODE REVIEW

**Comment by nikias** [comment]
Well maybe we can show them (in a readable form) if debug mode is enabled?

**Comment by Blefish** [comment]
Updated the pull request with fixes that allow iOS 12.1.1 beta to be restored on the device successfully as well. With these patches restoring works on all devices.

As for the checkpoint patch, I'm not sure. I haven't completely understood what the checkpoint messages print, they provide some index number along with some other stuff but it cluttered my output completely so I disabled it for now.

**Comment by Blefish** [comment]
I updated the request once again, I believe we used the wrong component "AppleLogo" all this time. It should have been "RestoreLogo", also noted here: https://github.com/xerub/idevicerestore/commit/73e504d3ce57083f660f9242c4293f67093c22f3

**Comment by pekn** [comment]
Has anyone tried idevicerestore with these patches using final iOS 12.1.1 - does it work?

**Comment by Blefish** [comment]
I have tried, it seems to work for me. Unfortunately I only tested on XS, XS Max and XR for now.

I did have issues with libplist, the recent changes broke something and I had to revert the changes there.

**Comment by Orbif** [comment]
@pekn I tried on Iphone 6s with 12.1.1.

@Blefish patch seems necessary because iPhone 6s doesn't enter in restore mode without it.

However, with the patch, idevicerestore crash at the step "Sending FDR Trust data now..."
[idevicerestore.txt](https://github.com/libimobiledevice/idevicerestore/files/2663536/idevicerestore.txt)

Any ideas ?

**Comment by Blefish** [comment]
@Orbif did you rebuild libplist?

I had issues with it, the last 3 commits were problematic. However I noticed @nikias pushed it again today, maybe it is fixed now?

**Comment by Kanong017** [comment]
@Blefish my iPhone XR restore finished,but Face ID don't work,Please update!

**Comment by Orbif** [comment]
@Blefish I applied the patch to an outdated version of the code source (october) and it worked ! 
I also think there is a problem with latest libplist sources.

@nikias With latest source code, I have a crash at the step "Sending FDR Trust data now...". 
There is a comment line 1683 of the restore.c file telling that an empty dict is sent at this step. 
Maybe an issue managing empty dict with new version of libplist ?

**Comment by Blefish** [comment]
@nikias I am currently using tip of libplist (which does not crash) at https://github.com/libimobiledevice/libplist/commit/2e67a01ba65ee3ac2a028dab2d636227616673ef

I ran it through GDB and found the problematic line here: https://github.com/libimobiledevice/libplist/blob/master/src/xplist.c#L359

```
xx@xx:~$ sudo gdb --args /usr/local/bin/idevicerestore  -C /xx/ios -i 955101104002E /xx/ios/iPhone11,2_12.1.1_16C50_Restore.ipsw
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/idevicerestore...done.
(gdb) run
Starting program: /usr/local/bin/idevicerestore -C /xx/ios -i 955101104002E /xx/ios/iPhone11,2_12.1.1_16C50_Restore.ipsw
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
NOTE: using cached version data
[New Thread 0x7ffff08ff700 (LWP 22726)]
Found device in Recovery mode
Identified device as d321ap, iPhone11,2
Extracting BuildManifest from IPSW
Product Version: 12.1.1
Product Build: 16C50 Major: 16
INFO: device serial number is xx
Device supports Image4: true
Variant: Customer Upgrade Install (IPSW)
This restore will update your device without losing data.
Using cached filesystem from '/xx/ios/iPhone11,2_12.1.1_16C50_Restore/048-40501-058.dmg'
Found ECID 2626802283708462
Getting ApNonce in recovery mode... 6a 13 41 a4 7f 50 82 1b 8b 6a 7e fc 24 9e 99 ee 1e 91 ec c6 21 0d 0e 6c 95 cd 9f 51 d5 b4 8c 52 
Trying to fetch new SHSH blob
Getting SepNonce in recovery mode... 8b 67 06 f7 9b 0b 42 6a 56 e7 3e 34 67 c5 a8 fd 15 6c f4 32 
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
[New Thread 0x7ffff00fe700 (LWP 22730)]
[Thread 0x7ffff00fe700 (LWP 22730) exited]
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
Extracting iBEC.d321.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (1054730 bytes)...
Recovery Mode Environment:
iBoot build-version=iBoot-4513.230.10
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@3x~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (20910 bytes)...
Extracting h11_ane_fw_quin.im4p...
Personalizing IMG4 component ANE...
Sending ANE (9621958 bytes)...
Extracting aopfw-iphone11aop.im4p...
Personalizing IMG4 component AOP...
Sending AOP (1396234 bytes)...
Extracting AppleAVE2FW.im4p...
Personalizing IMG4 component AVE...
Sending AVE (1267730 bytes)...
Extracting armfw_g11p.im4p...
Personalizing IMG4 component GFX...
Sending GFX (1672142 bytes)...
Extracting adc-petra-d3x.im4p...
Personalizing IMG4 component ISP...
Sending ISP (14611950 bytes)...
Extracting 048-40035-059.dmg.trustcache...
Personalizing IMG4 component RestoreTrustCache...
Sending RestoreTrustCache (11583 bytes)...
Extracting SmartIOFirmwareT8020.im4p...
Personalizing IMG4 component SIO...
Sending SIO (1276406 bytes)...
Extracting WirelessPower.iphone11.im4p...
Personalizing IMG4 component WCHFirmwareUpdater...
Sending WCHFirmwareUpdater (28913 bytes)...
ramdisk-size=0x20000000
Extracting 048-40035-059.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (107872781 bytes)...
Extracting DeviceTree.d321ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (193487 bytes)...
Extracting kernelcache.release.iphone11...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (17743680 bytes)...
About to restore device... 
Waiting for device...
[New Thread 0x7ffff00fe700 (LWP 22739)]
Device 00008020-000955101104002E is now connected in restore mode...
[Thread 0x7ffff00fe700 (LWP 22739) exited]
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device 00008020-000955101104002E has successfully entered restore mode
Hardware Information:
BoardID: 14
ChipID: 32800
UniqueChipID: 2626802283708462
ProductionMode: true
Previous restore exit status: 0x100
Starting FDR listener thread
[New Thread 0x7ffff00fe700 (LWP 22765)]
RequiredCapacity: 0xBE00000
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d321.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@3x~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@3x~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@3x~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@3x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@2436~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d321ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting liquiddetect@2436~iphone-lightning.im4p...
Personalizing IMG4 component Liquid...
Extracting lowpowermode@2436~iphone-lightning.im4p...
Personalizing IMG4 component LowPowerWallet0...
Extracting recoverymode@2436~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.d321.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Extracting sep-firmware.d321.RELEASE.im4p...
Personalizing IMG4 component RestoreSEP...
Extracting sep-firmware.d321.RELEASE.im4p...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Updating S3E Firmware (58)
Checking filesystems (15)
Checking filesystems (15)
About to send FDR Trust data...
Sending FDR Trust data now...

Thread 1 "idevicerestore" received signal SIGSEGV, Segmentation fault.
0x00007ffff7797e70 in node_to_xml (node=<optimized out>, 
    outbuf=<optimized out>, depth=<optimized out>)
    at /home/xx/xx/imobiledevice/libplist/src/xplist.c:359
359	/home/xx/xx/imobiledevice/libplist/src/xplist.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff7797e70 in node_to_xml (node=<optimized out>, 
    outbuf=<optimized out>, depth=<optimized out>)
    at /home/xx/xx/imobiledevice/libplist/src/xplist.c:359
#1  0x00007ffff7797594 in plist_to_xml (plist=plist@entry=0x5555569fcb20, 
    plist_xml=plist_xml@entry=0x7fffffffd370, 
    length=length@entry=0x7fffffffd364)
    at /home/xx/xx/imobiledevice/libplist/src/xplist.c:411
#2  0x00007ffff79aacf7 in internal_plist_send (client=0x555556a8c470, 
    plist=plist@entry=0x5555569fcb20, binary=binary@entry=0)
    at /home/xx/xx/imobiledevice/libimobiledevice/src/property_list_service.c:120
#3  0x00007ffff79ab347 in property_list_service_send_xml_plist (
    client=<optimized out>, plist=plist@entry=0x5555569fcb20)
    at /home/xx/xx/imobiledevice/libimobiledevice/src/property_list_service.c:154
#4  0x00007ffff79b93f6 in restored_send (client=client@entry=0x5555569e3ca0, 
    plist=plist@entry=0x5555569fcb20)
    at /home/xx/xx/imobiledevice/libimobiledevice/src/restore.c:159
#5  0x0000555555569bf8 in restore_send_fdr_trust_data (
    restore=restore@entry=0x5555569e3ca0, device=device@entry=0x555556998e10)
    at /home/xx/xx/imobiledevice/idevicerestore/src/restore.c:1695
#6  0x000055555556b26b in restore_handle_data_request_msg (
    client=client@entry=0x55555579a300, device=device@entry=0x555556998e10, 
---Type <return> to continue, or q <return> to quit---
```

**Comment by nikias** [comment]
Oh of course. Now it makes sense. Fixed it with commit https://github.com/libimobiledevice/libplist/commit/58334812f923fcf659d4a59ff32e1fe14787571d.

**Comment by Blefish** [comment]
Yes, it fixes the issue 👍

**Comment by Orbif** [comment]
It works ! Thank you @nikias and @Blefish.

@nikias Is it possible to pull Blefish patches to the master for compatibility with iOS 12.1 and 12.1.1 ?

**Comment by nikias** [comment]
@Orbif yes I will go through the patches pretty soon and see if there is anything that needs some fine tuning. I just didn't find the time yet.

**Comment by SamuelYvon** [comment]
@nikias Any update on when you expect to be done reviewing this PR? My organization would need the patch ASAP but I could make due with Blefish's patch.

**Comment by nikias** [comment]
Ok so I finally got around and merged most of the changes of this PR, sometimes slightly modified. This *should* work as expected, even without all the restore options set as in the first patch by @jduranc. Let me know if you are still seeing issues. Thanks for the contribution.

**Comment by Blefish** [comment]
Seems to work just fine! Thanks.

**Comment by nikias** [comment]
As reported in #243 there are still issues with latest devices. @blefish have you checked FaceID on those?

**Comment by timonline** [comment]
I think I am facing this issue on my iPhone 8 Plus restoring 12.4.1. Can share logs if it helps

**Pull request closed without merging**
