### PR TITLE
For upstream

### PR DESCRIPTION
**Pull request by zbalaton**
Misc cleanups and fixes
Please feel free to merge or cherry-pick.

### CODE REVIEW

**Comment by 4kzeng** [comment]
In the bm files,  iPhone7/7p has the node "SE,Firmware",  iPhone8/8p or higher has the  node "SE,Payload" .  So, do you confirm that select "SE,Firmware"  or "SE,Payload" depend on "SE,ChipID" ?

**Comment by nikias** [comment]
@4kzeng Yes it looks totally safe to me to rely on SE,ChipID.

**Comment by nikias** [comment]
Regarding the "Simplify restore function arguments" commit: I really prefer to keep the message as a separate parameter but the other optimizations (filesystem and device) seem ok to me.

The other commits are ok with the exception of the additional parameter to tss_request_add_se_tags as mentioned in my comment in #197.

**Comment by zbalaton** [comment]
Getting ChipID from parameters in tss_request_add_se_tags should be OK, I can change that when resubmitting this series. Any reason to keep message as a separate parameter though? I think this is part of the state and we already pass around the struct with all other state so adding message gets rid of this additional parameter and puts all state in the struct. If you really insist I could maybe split that patch to keep this separate from other optimisations.

**Comment by Blefish** [comment]
Any updates about the last patch?

**Comment by Blefish** [comment]
The last patch seems to have solved issues for me on iPhone 8.

**Comment by nikias** [comment]
I will merge that patch. As seen in #217 too it solves the issues with iPhone 8 / 8 plus.
I will not merge the function arguments patch since I just want to keep the message plist as an argument :)

**Comment by nikias** [comment]
merged all but the function arguments patch

**Pull request closed without merging**
