### PR TITLE
Remove .ipsw requirement when extracted IPSW is chosen as source

### PR DESCRIPTION
**Pull request by Orbif**
I noticed when extracted IPSW folder is chosen as source, the baseband is extracted from the .ipsw file anyway. 
This commit add the possibility to take the baseband from the extracted IPSW folder if present.

I think .ipsw file shouldn't be required if extracted IPSW folder contains all files.

### CODE REVIEW

**Comment by nikias** [comment]
Thanks. I just pushed a few commits that fix the sigaction -> signal issue on windows, but also makes sure CTRL+C still works in get_user_input().
Regarding the baseband, please check the original code again. If you have a fully extracted ipsw, the code here: https://github.com/libimobiledevice/idevicerestore/blob/master/src/ipsw.c#L225-L298 will check if it's the same file using realpath, and just returns 0 (success) in that case, without any copy operation.

**Comment by Orbif** [comment]
@nikias  Ok, so checking the path again is useless, but I think the baseband file need to be copied anyway.

When I try to restore with extracted IPSW folder (latest sources), I have this error : 
[idevicerestore-baseband-issue.txt](https://github.com/libimobiledevice/idevicerestore/files/3723566/idevicerestore-baseband-issue.txt)

 
I thought it was because .ipsw was missing, but it seems more complicated than that :
Looks like the baseband is extracted twice, and the second time, only a part of the original file is sent (the destination file is smaller than the source file).

This is why it works only when I copy the file, but maybe there is a better way to do it ?

**Comment by nikias** [comment]
Can you check if it works with this patch?
```
diff --git a/src/ipsw.c b/src/ipsw.c
index bd02bf9..d1d858b 100644
--- a/src/ipsw.c
+++ b/src/ipsw.c
@@ -231,10 +231,14 @@ int ipsw_extract_to_file_with_progress(const char* ipsw, const char* infile, con
                        ret = -1;
                        goto leave;
                } else {
+                       actual_outfile[0] = '\0';
                        if (realpath(outfile, actual_outfile) && (strcmp(actual_filepath, actual_outfile) == 0)) {
                                /* files are identical */
                                ret = 0;
                        } else {
+                               if (actual_outfile[0] == '\0') {
+                                       strcpy(actual_outfile, outfile);
+                               }
                                FILE *fi = fopen(actual_filepath, "rb");
                                if (!fi) {
                                        error("ERROR: fopen: %s: %s\n", actual_filepath, strerror(errno));
```
I realized if the realpath there fails, `actual_outfile` will not be set, hence it fails with the fopen without a filename.

**Comment by nikias** [comment]
Regarding the tmp filename and multiple extractions: The baseband file is stitched multiple times, at least for certain devices, and they differ each time. It is operating directly on the extracted zip file so this is mandatory.

**Comment by Orbif** [comment]
The restore is successful with this patch, tested with iPhone 6 plus and iPhone Xr.

Thank you 👍

**Comment by nikias** [comment]
Fixed with commit 38e7b85fdde8b3dbf697535f439c96c53564ee72.

**Pull request closed without merging**
