### PR TITLE
*added flags for iOS 12 compatibility.

### PR DESCRIPTION
**Pull request by jduranc**
* fix bootloop problem with iPhone 8 and iPhone 8P devices.

### CODE REVIEW

**Comment by jduranc** [comment]
> @jduranc Thank you for your work.
> I have faced an issue that the iPhone 8 does not boot up (the apple-logo blinks forever) even if idevicerestore finishes successfully.
> Is the "bootloop problem" that you said is the same issue?
> 
> I have faced this issue only once with iPhone 8 when restoring from iOS 11.4.1 to iOS 12.0.1.
> Once iPhone 8 is updated to iOS 12, I do not have this issue even without this patch.

Hi @rekyagis ,

Yes that was my issue with 8/8P models, but was fixed with this patch, do you have the problem after apply the patch?

**Comment by rekyagis** [comment]
@jduranc Thanks,
I am not sure whether we have this problem after applying the patch.
What I can say for sure is:
 - I had faced this issue before applying this patch. (iPhone8, iOS 11.4.1 -> 12.0.1)
 - I do not have this problem even without this patch if once iPhone8 have been updated iOS 12 or later (with iTunes).

I would like to test with iOS 11.4.1, but I can not make 11.4.1 since Apple has stopped signing it.

**Comment by jduranc** [comment]
> @jduranc Thanks,
> I am not sure whether we have this problem after applying the patch.
> What I can say for sure is:
> 
> * I had faced this issue before applying this patch. (iPhone8, iOS 11.4.1 -> 12.0.1)
> * I do not have this problem even without this patch if once iPhone8 have been updated iOS 12 or later (with iTunes).
> 
> I would like to test with iOS 11.4.1, but I can not make 11.4.1 since Apple has stopped signing it.

Yes, the problem was related to parameter TZ0RequiredCapacity that was not set when upgrading since 11.4.1 (or lower), but if you use iTunes the parameter its send and the update its applied, after that, the restore process works even without the patch. I tested the patch with models 6  to X, all works as expected upgrading from 11.4.1.

**Comment by pubsocent** [comment]
@jduranc I will be testing out this patch as I have several phones experiencing the boot loop problem.

**Comment by pubsocent** [comment]
@jduranc I tested on an iPhone 7 and it failed to work. 
It got into the Attempt 1 to connect to restore mode device... loop.

**Comment by rekyagis** [comment]
@jduranc Thanks, and sorry for late reply.
I understood your solution.
I have found iPhone8P/iOS11, and it have been successfully restored to iOS12 with your patch.
Thank you for your great work.

**Comment by nikias** [comment]
I found that adding `TZ0RequiredCapacity` is enough to make it work. Fix is already in master.

**Pull request closed without merging**
